#ifndef __BBPARAMETERS_H__
#define __BBPARAMETERS_H__


#define BBBOARD_POS_X					384
#define BBBOARD_POS_Y					512
#define BB_ELEMENT_OUTLINE_NUM			16
#define BB_ELEMENT_INLINE_NUM			8
#define BBSIZE_BOARD_WHOLE_RADIUS		200.0f
#define BBPARAM_BOARD_RETURNING_SPEED	0.1f


#endif